Fix configuration for tox 2.0.x
Using latest tox 2.0.x our tox jobs fail with following error:

tox.ConfigError: ConfigError: substitution key 'envbindir' not found

So, replace substitution key 'envbindir' with 'envdir' with suffix '/bin'.

Change-Id: I51a4aa7d66cf24ec89cd2c87c9ce902b919ba4b1
Closes-Bug: #1455066
(cherry picked from commit 095c81eb1e17f8d5b8c1c903d67792fdc4abbe9f)